version: "3.9"

services:
  web:
    build: .
    container_name: django_notification_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/notifications
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
