# Generated by Django 5.2.6 on 2025-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_notifications', '0002_notification_attempts_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_channels',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred channels in priority order', null=True),
        ),
    ]
